### ISSUE TITLE
Node List outputting numbers 1-40

### ISSUE THREAD

**Issue by datacrystals** [carboncopies/BrainGenix-UI#8]
When adding more than one node, sometimes the UI board outputs nonsense numbers incrimenting from 1-40 on the nodes list, and also the nodes refresh.

By refresh i mean that if you have 4 nodes named: a,b,c,d, the list shows this:

first frame:
a

second frame:
a
b

third frame:
a
b
c

fourth frame:
a
b
c
d

 and repeat...
Not sure if this is an APIServer issue or a client issue.

**Comment by allensulzen** [comment]
Sure. I was testing / prototyping with just one node. If you scale it up
and it's not ready you'll get some unexpected behavior.

**Comment by datacrystals** [comment]
Ok, sorry to bother you about it, but i just thought you may wish to know about it. For now, we'll just ignore it then.
